name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update file for 23f1000267@ds.study.iitm.ac.in
      run: |
        echo "Last run: $(date -u)" > daily-log.txt

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "23f1000267@ds.study.iitm.ac.in"
        git config --global user.name "DevSync Bot"
        git add daily-log.txt
        git commit -m "Daily update - $(date -u)" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git push origin HEAD:main

